server:
  servlet:
    context-path: /mortalkombat
  port: 8080

spring:
  # DB
  datasource:
    url: jdbc:postgresql://${POSTGRES:localhost:5432}/mortalkombat
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:pass}
  # JPA
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
          dialect: org.hibernate.dialect.PostgreSQL94Dialect
          integration:
            envers:
              enabled: true
        ddl-auto: validate

# Flyway
#spring:
#  flyway:
#    enabled=true
#    locations: classpath:db/migration
#    baseline-on-migrate: true

# Log
logging:
  level:
    org:
      hibernate:
        SQL: ${LOG_LEVEL:info}
        type:
          descriptor:
            sql.BasicBinder: ${LOG_LEVEL:info}
            sql: ${LOG_LEVEL:info}
    springframework: ${LOG_LEVEL:info}
